server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200, http://localhost:8080, http://localhost:8081"
            allowedMethods: "GET, POST, PUT, DELETE, HEAD, PATCH, OPTIONS"
            allowedHeaders: "Origin, Authorization, Content-Type, Accept"
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/uaa/**

        - id: course-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/courses/**

eureka:
  client:
    register-with-eureka: false

app:
  security:
    cors:
      allowedOrigins: http://localhost:4200, http://localhost:8080, http://localhost:8081
      allowedMethods: GET, POST, PUT, DELETE, HEAD, PATCH, OPTIONS
      allowedHeaders: Origin, Authorization, Content-Type, Accept
      allowCredentials: true
      maxAge: 3600
